# This file is managed by 'repo_helper'. Don't edit it directly.
---

name: "GitHub Releases"
on:
  push:
    branches: ["master"]
  schedule:
    - cron: 0 12 * * 2,4,6

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: domdfcoding/octocheese@master
        with:
          pypi_name: "repo_helper_sphinx_theme"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: startsWith(github.ref, 'refs/tags/') != true
